import { required } from "../../../../../../utils/formValidations";

export const formConfig = [
  {
    name: "name", // Match API response key
    label: { en: "Name", ar: "الاسم" },
    type: "text",
    value: "",
    isValid: undefined,
    errorMsg: "",
    validations: [required],
  },
  {
    name: "monthly_fee",
    label: { en: "Monthly Fee", ar: "الرسوم الشهرية" },
    type: "text",
    value: "",
    isValid: undefined,
    errorMsg: "",
    validations: [required],
  },
  {
    name: "start_shift",
    label: { en: "Start Shift", ar: "بداية الدوام" },
    type: "time",
    value: "",
    isValid: undefined,
    errorMsg: "",
    validations: [required],
  },
  {
    name: "end_shift",
    label: { en: "End Shift", ar: "نهاية الدوام" },
    type: "time",
    value: "",
    isValid: undefined,
    errorMsg: "",
    validations: [required],
  },
  {
    name: "program_color",
    label: { en: "Program Color", ar: "لون البرنامج" },
    type: "color",
    value: "#ffffff",
    isValid: true,
    errorMsg: "",
    validations: [required],
  },
  {
    name: "late_checkout_time",
    label: { en: "Late Checkout Time", ar: "وقت الخروج المتأخر" },
    type: "time",
    value: "",
    isValid: true,
    errorMsg: "",
    validations: [],
    optional: true,
  },
  {
    name: "late_checkout_fees",
    label: { en: "Late Checkout Fees", ar: "رسوم الخروج المتأخر" },
    type: "text",
    value: "",
    isValid: true,
    errorMsg: "",
    validations: [],
    optional: true,
  },
];
