import { required } from "../../../../utils/formValidations";

export const activityFormConfig = [
  {
    name: "activity_status",
    label: { en: "Activity Status", ar: "حالة النشاط" },
    type: "toggle",
    value: true,
    isValid: true,
    errorMsg: "",
    validations: [],
  },
  {
    name: "notify_parents",
    label: { en: "Notify Parents", ar: "إشعار الأهل" },
    type: "toggle",
    value: false,
    isValid: true,
    errorMsg: "",
    validations: [],
  },
  {
    name: "enable_file_upload",
    label: { en: "Enable file upload", ar: "تفعيل رفع الملفات" },
    type: "checkbox",
    value: false,
    isValid: true,
    errorMsg: "",
    validations: [],
  },
  {
    name: "enable_photo_video",
    label: { en: "Enable photo/video upload", ar: "تفعيل رفع الصور/الفيديو" },
    type: "checkbox",
    value: false,
    isValid: true,
    errorMsg: "",
    validations: [],
  },
  {
    name: "enable_draft_mode",
    label: { en: "Enable draft mode", ar: "تفعيل وضع المسودة" },
    type: "checkbox",
    value: false,
    isValid: true,
    errorMsg: "",
    validations: [],
  },
  {
    name: "enable_comments",
    label: { en: "Enable comments", ar: "تفعيل التعليقات" },
    type: "checkbox",
    value: false,
    isValid: true,
    errorMsg: "",
    validations: [],
  },
  {
    name: "requires_approval",
    label: { en: "Doesn't require approval", ar: "لا يتطلب موافقة" },
    type: "checkbox",
    value: true,
    isValid: true,
    errorMsg: "",
    validations: [],
  },
];